#!/system/xbin/bash
mount -o rw,remount /system
echo "Testing if we can write /etc/hosts.."

if [ ! -w /etc/hosts ]
then
 echo "Nope. Aborting. (Did you forget to remount /system?)"
 exit
fi

echo "Saving copy of system's original hosts file in /sdcard/hosts.BAK ..."
mv /etc/hosts /sdcard/hosts.BAK
touch /etc/hosts
echo "Done."

echo "Downloading ad-blocking hosts files..."
wget http://winhelp2002.mvps.org/hosts.txt >> /etc/hosts
wget http://hosts-file.net/download/hosts.txt >> /etc/hosts
wget http://someonewhocares.org/hosts/hosts >> /etc/hosts
echo "Done."

echo "########"
echo "## REMEMBER: Running root-shellcode from strangers is dangerous!"
echo "########"

echo "Parsing, cleaning, de-duplicating, sorting..."
echo "This can take while! (Up to 5 minutes, depending on your hardware.)"
sed -i -e 's/\r//' -e '/^127.0.0.1/!d' -e '/localhost/d' -e '/dropbox.com/d' -e 's/127.0.0.1/0.0.0.0/' -e 's/ \+/\t/' -e 's/#.*$//' -e 's/[ \t]*$//' /etc/hosts
echo "`uniq /etc/hosts`" > /etc/hosts
echo "Done."

mount -o ro,remount /system
echo "Finished."
